name: Build and deploy Angular App to Cloudfront
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: taskawsstestbucket
      DIST: dist
      REGION: eu-west-3
      DIST_ID: EBLL4C8EMFPC1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.REGION}}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          node --version
          npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync --delete ${{env.DIST}}/task-management/browser s3://${{env.BUCKET}}
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{env.DIST_ID}} --paths "/*"
